Repository OpenModelica/OMSimulator, pull requests merged in 2019-04, with the labels that each got.

#646 Run hostname for Windows agent
  Jenkinsfile
Labels: Jenkins

#648 Refactoring of signal derivatives
  src/OMSimulatorLib/ComponentFMUCS.cpp
  src/OMSimulatorLib/ComponentTable.cpp
  src/OMSimulatorLib/OMSimulator.cpp
  src/OMSimulatorLib/SignalDerivative.cpp
  src/OMSimulatorLib/SignalDerivative.h
Labels: refactoring

#652 Fix writing results
  src/OMSimulatorLib/MATWriter.cpp
Labels: bug-fix

#613 Fix bug in TLMBusConnector::getActualBus
  src/OMSimulatorLib/TLM/TLMBusConnector.cpp
Labels: bug-fix
