Repository OpenModelica/OMSimulator, pull requests merged in 2024-11, with the labels that each got.

#1342 no need to escape inside quotes
  Jenkinsfile
Labels: CI/MINGW_UCRT64

#1366 Fix lua binding for oms_setBoolean
  src/OMSimulatorLua/OMSimulatorLua.c
Labels: bug

#1367 Fix solver definitions in python bindings
  src/OMSimulatorPython/OMSimulator.py
Labels: bug

#1368 Fix edge case for time events and handle terminate requests by FMUs
  src/OMSimulatorLib/ComponentFMUCS.cpp
  src/OMSimulatorLib/SystemSC.cpp
  src/OMSimulatorLib/SystemWC.cpp
Labels: bug

#1372 add the path to git used by different testing computers
  Jenkinsfile
Labels: CI/MINGW_UCRT64

#1374 Fix conditional jump on uninitialised value
  include/OMSimulator/Types.h
  src/OMSimulatorLib/DirectedGraph.cpp
  src/OMSimulatorLib/SystemSC.cpp
  src/OMSimulatorLib/SystemWC.cpp
  testsuite/simulation/renameValues2.lua
Labels: bug

#1381 Update jenkins file
  Jenkinsfile
Labels: CI/macOS-arm64
